title:
  font_size: 16
  font_name: "Times New Roman"
  bold: true
  italic: false
  alignment: "CENTER"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 0
  space_after: 12

abstract:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "JUSTIFY"
  first_line_indent: 24
  line_spacing: 1.0
  space_before: 12
  space_after: 12

keywords:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "LEFT"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 6
  space_after: 6

heading1:
  font_size: 14
  font_name: "Times New Roman"
  bold: true
  italic: false
  alignment: "LEFT"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 12
  space_after: 12

heading2:
  font_size: 13
  font_name: "Times New Roman"
  bold: true
  italic: false
  alignment: "LEFT"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 12
  space_after: 12

body:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "JUSTIFY"
  first_line_indent: 24
  line_spacing: 1.5
  space_before: 0
  space_after: 0

references:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "LEFT"
  first_line_indent: -24
  line_spacing: 1.0
  space_before: 0
  space_after: 6

page_margin:
  top: 1.0
  bottom: 1.0
  left: 1.25
  right: 1.25

tables:
  style: "DEFAULT"
  alignment: "CENTER"
  width: null
  
  header_format:
    font_size: 10.5
    font_name: "Times New Roman"
    bold: true
    italic: false
    alignment: "CENTER"
    vertical_alignment: "CENTER"
    text_color: "000000"
    background_color: null
    line_spacing: 1.0
  
  data_format:
    font_size: 10.5
    font_name: "Times New Roman"
    bold: false
    italic: false
    alignment: "LEFT"
    vertical_alignment: "CENTER"
    text_color: "000000"
    background_color: null
    line_spacing: 1.0
  
  row_height: 12
  col_width: 100
  auto_fit: true
  
  border_size: 1.0
  border_color: "000000"
  cell_padding: 2
  spacing_before: 6
  spacing_after: 6

images:
  alignment: "CENTER"
  caption_font_size: 10.5
  caption_font_name: "Times New Roman"
  caption_alignment: "CENTER"
  space_before: 12
  space_after: 12

page_setup:
  # 页面大小（A4纸）
  page_width: 595.0
  page_height: 842.0
  
  # 页边距
  margin_top: 72.0
  margin_bottom: 72.0
  margin_left: 90.0
  margin_right: 90.0
  
  # 页眉页脚
  header_distance: 36.0
  footer_distance: 36.0
  different_first_page: true
  
  # 页码设置
  page_number_format: "ARABIC"
  page_number_start: 1
  page_number_position: "BOTTOM_CENTER"
  page_number_show_first: false
  
  # 分栏设置
  columns: 1
  column_spacing: 36.0
  
  # 纸张方向
  orientation: "PORTRAIT"

toc:
  title: "目录"
  title_font_size: 14
  title_font_name: "Times New Roman"
  title_bold: true
  title_alignment: "CENTER"
  
  level1_font_size: 12
  level1_font_name: "Times New Roman"
  level1_bold: false
  level1_indent: 0
  level1_tab_space: 24
  
  level2_font_size: 12
  level2_font_name: "Times New Roman"
  level2_bold: false
  level2_indent: 24
  level2_tab_space: 24
  
  line_spacing: 1.5
  space_before: 0
  space_after: 12
  show_page_numbers: true
  right_align_page_numbers: true
  include_heading_levels: 2
  start_on_new_page: true

# ... 其他部分的格式定义 ... 