title:
  font_size: 16
  font_name: "Times New Roman"
  bold: true
  italic: false
  alignment: "CENTER"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 0
  space_after: 12

abstract:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "JUSTIFY"
  first_line_indent: 24
  line_spacing: 1.0
  space_before: 12
  space_after: 12

keywords:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "LEFT"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 6
  space_after: 6

heading1:
  font_size: 14
  font_name: "Times New Roman"
  bold: true
  italic: false
  alignment: "LEFT"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 12
  space_after: 12

heading2:
  font_size: 13
  font_name: "Times New Roman"
  bold: true
  italic: false
  alignment: "LEFT"
  first_line_indent: 0
  line_spacing: 1.0
  space_before: 12
  space_after: 12

body:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "JUSTIFY"
  first_line_indent: 24
  line_spacing: 1.5
  space_before: 0
  space_after: 0

references:
  font_size: 12
  font_name: "Times New Roman"
  bold: false
  italic: false
  alignment: "LEFT"
  first_line_indent: -24
  line_spacing: 1.0
  space_before: 0
  space_after: 6

page_margin:
  top: 1.0
  bottom: 1.0
  left: 1.25
  right: 1.25

tables:
  style: "DEFAULT"
  alignment: "CENTER"
  width: null
  
  header_format:
    font_size: 10.5
    font_name: "Times New Roman"
    bold: true
    italic: false
    alignment: "CENTER"
    vertical_alignment: "CENTER"
    text_color: "000000"
    background_color: null
    line_spacing: 1.0
  
  data_format:
    font_size: 10.5
    font_name: "Times New Roman"
    bold: false
    italic: false
    alignment: "LEFT"
    vertical_alignment: "CENTER"
    text_color: "000000"
    background_color: null
    line_spacing: 1.0
  
  row_height: 12
  col_width: 100
  auto_fit: true
  
  border_size: 1.0
  border_color: "000000"
  borders:
    top: true
    bottom: true
    left: true
    right: true
    inside_h: true
    inside_v: true
  
  cell_padding: 2
  spacing_before: 6
  spacing_after: 6

images:
  alignment: "CENTER"
  caption_font_size: 10.5
  caption_font_name: "Times New Roman"
  caption_alignment: "CENTER"
  space_before: 12
  space_after: 12

# ... 其他部分的格式定义 ... 